### ISSUE TITLE
LangChain - ImportError : cannot import name Executable from sqlalchemy

### ISSUE THREAD

**Issue by hab6** [ActianCorp/sqlalchemy-ingres#32]
The following langchain test case succeeds when run with SQLAlchemy `2.0.27` but fails when run with SQLAlchemy `1.4.51`.

#### Test Case

    import os
    import sys
    import sqlalchemy
    import sqlalchemy_ingres
    import langchain
    from langchain.sql_database import SQLDatabase
    print('Python %s on %s' % (sys.version, sys.platform))
    print('SQLAlchemy %r' % sqlalchemy.__version__)
    print('langchain %r' % langchain.__version__)
    driver_name = os.environ.get('SQLALCHEMY_INGRES_ODBC_DRIVER_NAME') or 'Actian'
    print('SQLALCHEMY_INGRES_ODBC_DRIVER_NAME %r' % driver_name)
    con_str = os.environ['DATABASE_URI']
    db = SQLDatabase.from_uri(con_str)

#### Test Environment Versions

    C:\>python -V
    Python 3.10.7

    langchain           0.1.7
    langchain-community 0.0.20
    langchain-core      0.1.23
    langsmith           0.0.87
    pyodbc              5.1.0
    pypyodbc            1.3.6
    setuptools          63.2.0
    SQLAlchemy          1.4.51
    sqlalchemy-ingres   0.0.5.dev1

#### Stack Dump & Error

    C:\test> python repro1.py
    Traceback (most recent call last):
      File "C:\test\repro1.py", line 9, in <module>
        from langchain.sql_database import SQLDatabase
      File "C:\test\.venv\lib\site-packages\langchain\sql_database.py",
         line 2, in <module>
        from langchain_community.utilities.sql_database import SQLDatabase
      File "C:\test\.venv\lib\site-packages\langchain_community\utilities\sql_database.py",
         line 9, in <module>
        from sqlalchemy import (
    ImportError: cannot import name 'Executable' from 'sqlalchemy'
         (C:\test\.venv\lib\site-packages\sqlalchemy\__init__.py)

**Comment by hab6** [comment]
This problem can be reproduced with the single import line:

    from langchain.sql_database import SQLDatabase

e.g.

Works with SQLAlchemy 2.0.24

    C:\test>pip list | grep SQLAlchemy
    SQLAlchemy          2.0.27
    C:\test>python
    Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from langchain.sql_database import SQLDatabase
    >>>


Fails with SQLAlchemy 1.4.51

    C:\test>pip list | grep SQLAlchemy
    SQLAlchemy          1.4.51
    C:\test>python
    Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from langchain.sql_database import SQLDatabase
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Users\mhabiger\Data\work\saDialect\github32\.venv\lib\site-packages\langchain\sql_database.py", line 2, in <module>
        from langchain_community.utilities.sql_database import SQLDatabase
      File "C:\Users\mhabiger\Data\work\saDialect\github32\.venv\lib\site-packages\langchain_community\utilities\sql_database.py", line 9, in <module>
        from sqlalchemy import (
    ImportError: cannot import name 'Executable' from 'sqlalchemy' (C:\Users\mhabiger\Data\work\saDialect\github32\.venv\lib\site-packages\sqlalchemy\__init__.py)
    >>>

**Comment by hab6** [comment]
Key pieces of the SQLAlchemy support for LangChain are implemented in [sql_database.py](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/utilities/sql_database.py)

The langchain current version ([0.0.20](https://github.com/langchain-ai/langchain/blob/75465a2a3cc7643a3d3031d9854cc0d7a21fa083/libs/cli/langchain_cli/cli.py#L11)) has this requirement (per [link1](https://github.com/langchain-ai/langchain/blob/75465a2a3cc7643a3d3031d9854cc0d7a21fa083/libs/community/pyproject.toml#L13), [link2](https://github.com/langchain-ai/langchain/blob/75465a2a3cc7643a3d3031d9854cc0d7a21fa083/libs/community/pyproject.toml#L13)):

    SQLAlchemy = ">=1.4,<3"

So, this version (`0.0.20`) of LangChain should work with SQLAlchemy `1.4.51`.

**Comment by hab6** [comment]
This is a bug in **langchain** which causes an incompatibility with SQLAlchemy 1.x.

Langchain PR [17191](https://github.com/langchain-ai/langchain/pull/17191) introduced the problem when merged to the master branch on Feb 7, 2024.

Langchain issue [17519](https://github.com/langchain-ai/langchain/issues/17519) was opened on Feb 14, 2024 with a number of people encountering the same problem.

The fix was merged to master via [17520](https://github.com/langchain-ai/langchain/pull/17520)

In the meantime, the workaround is to download langchain from `0.1.7` to `0.1.6`. This works for me.

**Comment by clach04** [comment]
nice work!

**Comment by vayvay0993** [comment]
> In the meantime, the workaround is to download langchain from `0.1.7` to `0.1.6`. This works for me.

I've tried to l install langchain of 0.1.6 version and my sqlalchemy version is 1.4.46,
but I still got import error while try to import `create_extraction_chain`

`ImportError: cannot import name 'Executable' from 'sqlalchemy'`

**Comment by clach04** [comment]
> This is a bug in **langchain** which causes an incompatibility with SQLAlchemy 1.x.
> 
> Langchain PR [17191](https://github.com/langchain-ai/langchain/pull/17191) introduced the problem when merged to the master branch on Feb 7, 2024.
> 
> Langchain issue [17519](https://github.com/langchain-ai/langchain/issues/17519) was opened on Feb 14, 2024 with a number of people encountering the same problem.
> 
> The fix was merged to master via [17520](https://github.com/langchain-ai/langchain/pull/17520)
> 
> In the meantime, the workaround is to download langchain from `0.1.7` to `0.1.6`. This works for me.

@hab6 Is the other workaround to pull headrevs of langchain that includes the fix?

@vayvay0993 you may need to check in with the langchain product, it doesn't seem like the issue relates to this project based on the traceback and @hab6 research.

**Comment by hab6** [comment]
@vayvay0993 The import works for me with these package versions.

    (.venv) λ le | grep -e langchain -e chemy
    langchain           0.1.6
    langchain-community 0.0.19
    langchain-core      0.1.23
    SQLAlchemy          1.4.46
    sqlalchemy-ingres   0.0.4

    (.venv) λ python
    Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from langchain.chains import create_extraction_chain
    >>>

Could you please retest and see if this works for you?

**Comment by vayvay0993** [comment]
Yes, I really appreciate your help! 🙏

**Comment by hab6** [comment]
This issue is now fixed with Langchain version `0.1.8` released to [PyPi](https://pypi.org/project/langchain/) today. With these versions installed:

    langchain           0.1.8
    langchain-community 0.0.21

SQLAlchemy `1.4.51` no longer reports the `ImportError`.
